# Generated by Django 4.2.4 on 2023-11-24 18:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userclientmodel",
            name="email",
            field=models.EmailField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="userclientmodel",
            name="first_name",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="userclientmodel",
            name="last_name",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="userclientmodel",
            name="password",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="userclientmodel",
            name="username",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="userclientmodel",
            name="birthdate",
            field=models.DateField(default=datetime.date.today, max_length=10),
        ),
        migrations.AlterField(
            model_name="userclientmodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userclientmodel",
            name="phone_number",
            field=models.CharField(
                blank=True, default=None, max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userclientmodel",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
