# Generated by Django 4.2.4 on 2023-09-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0003_productmodel_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="state",
            field=models.CharField(
                choices=[
                    ("PU", "PUBLICADO"),
                    ("BR", "BORRADOR"),
                    ("PR", "PRIVADO"),
                ],
                default="BR",
                max_length=2,
            ),
        ),
    ]
